### ISSUE TITLE
Jekyll migration checklist

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website#472]
Checklist for migrating the website from Pelican to Jekyll (see #462)

- [x] Move posts
- [x] Move pages
- [x] Update `summary` to `description`
- [x] Update `cover_image` to `background`
- [x] Verify h1 titles
- [x] Remove tags except for IG, TG, MG and posts
- [x] Enable GitHub link in header
- [x] Enable website link in header
- [x] Verify hidden pages
- [x] Check internal links
- [x] Create main nav
- [x] Create conf nav
- [x] Create TDWG 2020 nav
- [x] Create TDWG 2021 nav
- [x] Create TDWG 2022 nav
- [x] Create about nav
- [x] Create news page
- [x] Create standards page
- [x] Create community page
- [x] Create home page
- [x] Verify static files
